/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct packet {
	struct {
		u_int chars_len;
		char *chars_val;
	} chars;
	int idx;
};
typedef struct packet packet;

struct serverPacket {
	struct {
		u_int chars_len;
		char *chars_val;
	} chars;
	int amt;
};
typedef struct serverPacket serverPacket;

typedef struct {
	u_int sPacket_len;
	serverPacket *sPacket_val;
} sPacket;

#define PROG 0x30009999
#define VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getMessages 1
extern  sPacket * getmessages_1(char **, CLIENT *);
extern  sPacket * getmessages_1_svc(char **, struct svc_req *);
#define sendMessage 2
extern  int * sendmessage_1(packet *, CLIENT *);
extern  int * sendmessage_1_svc(packet *, struct svc_req *);
#define connect 3
extern  int * connect_1(char **, CLIENT *);
extern  int * connect_1_svc(char **, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getMessages 1
extern  sPacket * getmessages_1();
extern  sPacket * getmessages_1_svc();
#define sendMessage 2
extern  int * sendmessage_1();
extern  int * sendmessage_1_svc();
#define connect 3
extern  int * connect_1();
extern  int * connect_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_packet (XDR *, packet*);
extern  bool_t xdr_serverPacket (XDR *, serverPacket*);
extern  bool_t xdr_sPacket (XDR *, sPacket*);

#else /* K&R C */
extern bool_t xdr_packet ();
extern bool_t xdr_serverPacket ();
extern bool_t xdr_sPacket ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
