/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hw.h"

bool_t
xdr_packet (XDR *xdrs, packet *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->chars.chars_val, (u_int *) &objp->chars.chars_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idx))
		 return FALSE;
	return TRUE;
}
